sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: dqxCBDiSIdJUbGszfdkfs//lcFSudhmmNvT6WIOOmMzzK3p5Uk4hRscc01SeTaZvnFIhCysyDh00f7W6CxkOIQjwMxMj7rbXNeJkVJvYfcelFr95vLl2vQ7kB0KGgyFk57BIc12YN9mOY9AGoRHke6ALxG5A1pYfTXmUxqFIr1zwaPllg9/n2AbkeKgBcuXga/4b2we53T/Ul60OejxSC1kU9etAw98sLdTMZChfyGYevJbHQ+0H/vsxOR8WdXVSsphEB2R/yy7g4Qi/1ypo2qNE0+q/qzwwnwZ8Oq2kMfW8xNR8lPjI4FxitqhUzZH+COR81DleRdayrU3+Q6HgL0q7UZipGTwCZQfoeMeuQGfoNxhJKJezDL1TJpS3/xmWfgrjJXZbvtWQhm7B7JzytAVdVD9bzD3ADWf/LeqmXPvF7Vz9TxpFMjy8Uxcyt5TbTFl+7S+RG9N7zOcwz/R9XpmCs0RutGhfY18NRW0tZlP+l1OixqMBawWcb5ghijGwD4upa6gOv/leVC8izssA1FP/u3J0DeZRhpCHSXls9Gu+QqoAL7inyv0T6au44vN1yWdq9M4paKpaiiTY10XdSdQ7jZ6Rbuo0jBOTz5BVl5ZmBw49k9j1YMl2Gw8LHvkWabGUr9gE6yOnZT6Zc8OnY/jY+VulcKQqgMptdl4sO0U=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Bound-to-Rise--Or-Up-the-Ladder_5977
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy